---
author:
  - 'Matt Cashner (sungo@pobox.com)'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Session-Cascading
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  POE: 0.19
version: 1.04
